In [1]:
import numpy as np

### Goal: This notebook will help you coding dz=a-y and cross entropy loss without using one-hot y

In [6]:
y=np.array([0,0,1,1,2,2,2])
print('acutal:',y)

acutal: [0 0 1 1 2 2 2]


In [3]:
#prediction
a=np.array([ [0.3, 0.5, 0.2], [0.1, 0.7, 0.2], [0.15, 0.05, 0.8], [0.35, 0.5, 0.15], [0.03, 0.17, 0.8], [0.93, 0.05, 0.02], [0.7, 0.12, 0.18]])

In [8]:
print('prediction:\n',a)

prediction:
 [[0.3  0.5  0.2 ]
 [0.1  0.7  0.2 ]
 [0.15 0.05 0.8 ]
 [0.35 0.5  0.15]
 [0.03 0.17 0.8 ]
 [0.93 0.05 0.02]
 [0.7  0.12 0.18]]


<b>Calculate cross-entropy loss</b>

In [15]:
#converting onehot
N=7
y_onehot=np.zeros((N, 3))
y_onehot[ range(N), y]=1
print(y_onehot)

[[1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]]


In [24]:
L=-np.sum( y_onehot*np.log(a) , axis=1, keepdims=True)
print(L)

[[1.2039728 ]
 [2.30258509]
 [2.99573227]
 [0.69314718]
 [0.22314355]
 [3.91202301]
 [1.71479843]]


<b>Calculate cross-entropy loss without one-hot</b> <br>
<b>Note: without using loop</b>

In [20]:
#your code goes here

<b>Calculate dz=a-y_onehot using one-hot y</b>

In [22]:
dz=a-y_onehot
dz

array([[-0.7 ,  0.5 ,  0.2 ],
       [-0.9 ,  0.7 ,  0.2 ],
       [ 0.15, -0.95,  0.8 ],
       [ 0.35, -0.5 ,  0.15],
       [ 0.03,  0.17, -0.2 ],
       [ 0.93,  0.05, -0.98],
       [ 0.7 ,  0.12, -0.82]])

<b>Task: Calculate dz=a-y without one-hot y</b>
 <br>
<b>Note: without using loop</b>

In [25]:
#your code goes here